-- Düzenli giderler için aya özel tutar override'ı.
--
-- Amaç: giderin "normal" tutarı (recurring_expenses.amount) sabit kalsın,
-- ama belirli bir ayda farklı ödenen tutar ayrıca kaydedilebilsin.
-- Örnek: Garanti KK normalde 125.000, Ağustos 2026'da 200.000.
--
-- Her (gider, yıl, ay) için en fazla bir override olur; tekrar yazıldığında
-- güncellenir (upsert). Override silinince gider otomatik base tutara döner.

create table if not exists recurring_expense_overrides (
  id bigint generated by default as identity primary key,
  expense_id bigint not null references recurring_expenses(id) on delete cascade,
  period_year int not null,
  period_month int not null check (period_month between 1 and 12),
  amount numeric not null,
  note text,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (expense_id, period_year, period_month)
);

create index if not exists recurring_expense_overrides_period_idx
  on recurring_expense_overrides (period_year, period_month);

-- Diğer tablolarla aynı RLS modeli (bkz. 20260702_rls_user_id.sql)
alter table recurring_expense_overrides enable row level security;
drop policy if exists recurring_expense_overrides_owner_all on recurring_expense_overrides;
create policy recurring_expense_overrides_owner_all on recurring_expense_overrides
  for all to authenticated
  using (user_id is null or user_id = auth.uid())
  with check (user_id is null or user_id = auth.uid());
