-- Web Push abonelikleri: her tarayici/cihaz icin bir kayit.
-- Supabase Dashboard > SQL Editor'de calistirin.
create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

-- Not: Diger tablolarda henuz RLS kullanilmadigi icin burada da acik birakildi.
-- RLS'i tum tablolarda topluca etkinlestirirken bu tabloya sadece
-- service_role erisimi yeterlidir (istemci dogrudan erismez, API uzerinden gecer).
